# 语言
language: python
python:
  - 3.6

branches:
  only:
  - master

# 何时发邮件: https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    recipients:
      - zhengxinzhibs@gmail.com
    on_success: always # default: change
    on_failure: always # default: alway

cache:
  directories:
  - build
  yarn: true

before_install:
- export TZ='Asia/Shanghai'  # 设置时区

install:
 - pip install -r blog.requirement

# build 生成的最终网站会在site目录内，–clean参数保证构建的时候site文件夹内没有多余文件
script:
- mkdocs build -clean

# 部署
after_script:
   - cd site/
   - git init
   - git config user.name "spaceplayer"
   - git config user.email "zhengxinzhibs@gmail.com"
   - git add .
   - git commit -m "Update sphinx By TravisCI With Build $TRAVIS_BUILD_NUMBER"
   - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

# 环境变量
env:
 global:
   # Coding Pages
  - GH_REF: github.com/spaceplayer/spaceplayer.github.io
